name: Review Games

on: 
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Game-Review-using-bots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot_number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    name: Bot ${{ matrix.bot_number }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        pip install requests playwright
        python -m playwright install chromium
    - name: Find Unreviewed Games
      run: python game_finder.py
      env:
        PLAYER: ${{ secrets.PLAYER }}
    - name: Simulate Display
      run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1920x1080x24 &
    - name: Get Identifiers
      env:
        BOTS: ${{ secrets.BOTS }}
      run: |
        echo "$BOTS" > bots.json
        USER=$(jq -r ".bot${{ matrix.bot_number }}.user" bots.json)
        PASS=$(jq -r ".bot${{ matrix.bot_number }}.pass" bots.json)
        echo "USERNAME=$USER" >> $GITHUB_ENV
        echo "PASSWORD=$PASS" >> $GITHUB_ENV
    - name: Review Game
      run: python reviewer.py
      env:
        BOT_NUMBER: ${{ matrix.bot_number }}
        DISPLAY: ":99.0"