name: Automatic Review

on: 
  schedule:
  - cron: '0 0 * * *'

jobs:
  Review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install requests playwright
          python -m playwright install chromium
      - name: Get BOTS
        env:
          BOTS: ${{ secrets.BOTS }}
        run: |
          echo "$BOTS" > bots.json
      - name: Find Unreviewed Games
        run: python game_finder.py
        env:
          PLAYER: ${{ secrets.PLAYER }}
      - name: Simulate Display
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1920x1080x24 &
      - name: Review Game
        run: python reviewer.py
        env:
            DISPLAY: ":99.0"